# Generated by Django 5.2 on 2025-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='post_images/defaultImage.jpg', upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
